// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbsNeNLIjB1fN0vYSf_koFA4kDlVWZUgg',
    appId: '1:391945895831:web:19b22eb820e922e4e00ed2',
    messagingSenderId: '391945895831',
    projectId: 'authamtication-app',
    authDomain: 'authamtication-app.firebaseapp.com',
    storageBucket: 'authamtication-app.appspot.com',
    measurementId: 'G-7QCLE390ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCf07doJDTDBmWLWGkI22c75AijH-dCpw',
    appId: '1:391945895831:android:21276b63b2a5381ce00ed2',
    messagingSenderId: '391945895831',
    projectId: 'authamtication-app',
    storageBucket: 'authamtication-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOEMlac-gvGK-ajPOMBth80E2owiynE1o',
    appId: '1:391945895831:ios:94555c242c7173eae00ed2',
    messagingSenderId: '391945895831',
    projectId: 'authamtication-app',
    storageBucket: 'authamtication-app.appspot.com',
    iosBundleId: 'com.example.viva2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOEMlac-gvGK-ajPOMBth80E2owiynE1o',
    appId: '1:391945895831:ios:d99ef527c09f2829e00ed2',
    messagingSenderId: '391945895831',
    projectId: 'authamtication-app',
    storageBucket: 'authamtication-app.appspot.com',
    iosBundleId: 'com.example.viva2.RunnerTests',
  );
}
